services:
  server:
    build:
      context: ..
      args:
        NEXT_PUBLIC_CIFARM_CORE_KEY: ${NEXT_PUBLIC_CIFARM_CORE_KEY}
        NEXT_PUBLIC_CIFARM_CORE_HOST: ${NEXT_PUBLIC_CIFARM_CORE_HOST}
        NEXT_PUBLIC_CIFARM_CORE_PORT: ${NEXT_PUBLIC_CIFARM_CORE_PORT}
        NEXT_PUBLIC_CIFARM_CORE_USE_SSL: ${NEXT_PUBLIC_CIFARM_CORE_USE_SSL}
        NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL: ${NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL}
        NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL: ${NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL}
    
        NEXT_PUBLIC_CIFARM_BASE_URL: ${NEXT_PUBLIC_CIFARM_BASE_URL}
        NEXT_PUBLIC_CIFARM_LOADER_NAME: ${NEXT_PUBLIC_CIFARM_LOADER_NAME}
        NEXT_PUBLIC_CIFARM_DATA_NAME: ${NEXT_PUBLIC_CIFARM_DATA_NAME}
        NEXT_PUBLIC_CIFARM_FRAMEWORK_NAME: ${NEXT_PUBLIC_CIFARM_FRAMEWORK_NAME}
        NEXT_PUBLIC_CIFARM_WASM_NAME: ${NEXT_PUBLIC_CIFARM_WASM_NAME}

        NEXT_PUBLIC_BASE_PERIPHERY_API_URL: ${NEXT_PUBLIC_BASE_PERIPHERY_API_URL}
        NEXT_PUBLIC_BASE_PERIPHERY_GRAPHQL_URL: ${NEXT_PUBLIC_BASE_PERIPHERY_GRAPHQL_URL}

        NEXT_PUBLIC_TESTNET_NEAR_MAIN_ACCOUNT_ID: ${NEXT_PUBLIC_TESTNET_NEAR_MAIN_ACCOUNT_ID}
        NEXT_PUBLIC_MAINNET_NEAR_MAIN_ACCOUNT_ID: ${NEXT_PUBLIC_MAINNET_NEAR_MAIN_ACCOUNT_ID}
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3053:3000
