
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    env:
      NODE_ENV: ${{vars.NODE_ENV}}
      
      NEXT_PUBLIC_CIFARM_CORE_KEY: ${{vars.NEXT_PUBLIC_CIFARM_CORE_KEY}}
      NEXT_PUBLIC_CIFARM_CORE_HOST: ${{vars.NEXT_PUBLIC_CIFARM_CORE_HOST}}
      NEXT_PUBLIC_CIFARM_CORE_PORT: ${{vars.NEXT_PUBLIC_CIFARM_CORE_PORT}}
      NEXT_PUBLIC_CIFARM_CORE_USE_SSL: ${{vars.NEXT_PUBLIC_CIFARM_CORE_USE_SSL}}
      NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL: ${{vars.NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL}}
      NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL: ${{vars.NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL}}
      
      NEXT_PUBLIC_CIFARM_BASE_URL: ${{vars.NEXT_PUBLIC_CIFARM_BASE_URL}}
      NEXT_PUBLIC_CIFARM_LOADER_NAME: ${{vars.NEXT_PUBLIC_CIFARM_LOADER_NAME}}
      NEXT_PUBLIC_CIFARM_DATA_NAME: ${{vars.NEXT_PUBLIC_CIFARM_DATA_NAME}}
      NEXT_PUBLIC_CIFARM_FRAMEWORK_NAME: ${{vars.NEXT_PUBLIC_CIFARM_FRAMEWORK_NAME}} 
      NEXT_PUBLIC_CIFARM_WASM_NAME: ${{vars.NEXT_PUBLIC_CIFARM_WASM_NAME}}

      NEXT_PUBLIC_BASE_PERIPHERY_API_URL: ${{vars.NEXT_PUBLIC_BASE_PERIPHERY_API_URL}}
      NEXT_PUBLIC_BASE_PERIPHERY_GRAPHQL_URL: ${{vars.NEXT_PUBLIC_BASE_PERIPHERY_GRAPHQL_URL}}

      NEXT_PUBLIC_TESTNET_NEAR_MAIN_ACCOUNT_ID: ${{vars.NEXT_PUBLIC_TESTNET_NEAR_MAIN_ACCOUNT_ID}}
      NEXT_PUBLIC_MAINNET_NEAR_MAIN_ACCOUNT_ID: ${{vars.NEXT_PUBLIC_MAINNET_NEAR_MAIN_ACCOUNT_ID}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
 
    - name: Run `docker compose`
      run: docker compose -f docker/production.yaml -p ci-wallet up --build -d 
